url: https://xarkenz.github.io/icd

title: Introduction to Compiler Design
description: Spring 2024
author:
  name: Sean Clarke
  email: sean.clarke@utdallas.edu

remote_theme: jekyll/minima

header_pages:
  - signup.md
  - about.md
  - prereqs.md

minima:
  skin: auto

collections:
  lectures_24s:
    output: true
    permalink: /lectures/:title
