url: https://xarkenz.github.io/icd

title: Introduction to Compiler Design
description: Spring 2024
author:
  name: Sean Clarke
  email: sean.clarke@utdallas.edu

remote_theme: jekyll/minima

header_pages:
  - syllabus.md
  - signup.md

minima:
  skin: auto